# Generated by Django 2.0.7 on 2018-07-09 23:51

import ckeditor.fields
import core.models.ModelBase
import core.utils.imagens
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to=core.utils.imagens.get_file_path)),
                ('imagem_thumbnail', models.ImageField(blank=True, null=True, upload_to=core.utils.imagens.get_thumbnail_path)),
                ('capa', models.BooleanField(default=False)),
                ('credito', models.CharField(blank=True, max_length=120, null=True, verbose_name='Crédito')),
            ],
            options={
                'verbose_name': 'Foto Galeria',
                'verbose_name_plural': 'Fotos Galeria',
                'ordering': ['titulo'],
            },
            bases=(core.models.ModelBase.DeleteImagemThumbMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('ativa', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('texto', ckeditor.fields.RichTextField()),
                ('pousada', models.BooleanField(default=False, verbose_name='Fotos da pousada')),
                ('criado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='galerias_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galerias_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
                'ordering': ['-data_publicacao', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='fotogaleria',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='galerias.Galeria'),
        ),
    ]
