# Generated by Django 2.0.4 on 2018-05-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Mesorregiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesorregioes', to='core.Estado')),
            ],
            options={
                'verbose_name': 'Mesorregião',
                'verbose_name_plural': 'Mesorregiões',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Microrregiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('mesorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microrregioes', to='core.Mesorregiao')),
            ],
            options={
                'verbose_name': 'Microrregião',
                'verbose_name_plural': 'Microrregiões',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('microrregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.Microrregiao')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.Regiao'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='core.Municipio'),
        ),
    ]
