# Generated by Django 2.0.4 on 2018-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='codigo',
            field=models.CharField(default='', max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='codigo',
            field=models.CharField(default='', max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesorregiao',
            name='codigo',
            field=models.CharField(default='', max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microrregiao',
            name='codigo',
            field=models.CharField(default='', max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_completo',
            field=models.CharField(default='', max_length=10, verbose_name='Código Completo'),
            preserve_default=False,
        ),
    ]
