# Generated by Django 2.0.7 on 2018-08-08 15:18

import ckeditor_uploader.fields
import core.models.ModelBase
import core.utils.imagens
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('descricao', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('criado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_noticia_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_noticia_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Notícia',
                'verbose_name_plural': 'Categorias de Notícia',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='FotoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Título')),
                ('credito', models.CharField(blank=True, max_length=120, null=True, verbose_name='Crédito')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to=core.utils.imagens.get_file_path)),
                ('imagem_thumbnail', models.ImageField(blank=True, null=True, upload_to=core.utils.imagens.get_thumbnail_path)),
                ('capa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Foto Notícia',
                'verbose_name_plural': 'Fotos Notícia',
                'ordering': ['titulo'],
            },
            bases=(core.models.ModelBase.DeleteImagemThumbMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aprovada'), (2, 'Para Aprovação'), (3, 'Em Autoria')], default=3)),
                ('credito', models.CharField(blank=True, max_length=60, null=True, verbose_name='Crédito')),
                ('fonte', models.CharField(blank=True, max_length=60, null=True)),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Subtítulo')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Amigável')),
                ('resumo', models.TextField(blank=True, max_length=600, null=True)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
                ('destaque', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Destaque 1'), (2, 'Destaque 2'), (3, 'Destaque 3')], null=True, verbose_name='Local de Destaque')),
                ('data_destaque', models.DateTimeField(blank=True, null=True)),
                ('aprovado_em', models.DateTimeField(null=True)),
                ('aprovado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.Categoria')),
                ('criado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_modificadas', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao', 'titulo'],
                'permissions': (('aprovar_noticia', 'Usuário pode aprovar uma notícia para exibir no portal'),),
            },
        ),
        migrations.AddField(
            model_name='fotonoticia',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='noticias.Noticia'),
        ),
    ]
