# Generated by Django 2.0.7 on 2018-08-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('texto', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Em Análise'), (2, 'Aprovado'), (3, 'Recusado')], default=1)),
                ('aprovado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.Noticia')),
            ],
            options={
                'verbose_name': 'Comentário Notícia',
                'verbose_name_plural': 'Comentários Notícia',
                'ordering': ['-created'],
            },
        ),
    ]
