# Generated by Django 2.0.7 on 2018-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
