# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20170127_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='É Administrador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
