# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:57
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def loadfixture(apps, schema_editor):
    call_command('loaddata', 'grupos.json')

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20170127_1731'),
    ]

    operations = [
        #migrations.RunPython(loadfixture),
    ]
